### ISSUE TITLE
正常启动后，首页出不来页面，404

### ISSUE THREAD

**Issue by BruceOuyang** [vito16/shop#26]
刚拉下来的代码，设置好数据库之后，端口设置为80，其它地方未改动过，运行Application.main启动ok

访问：http://localhost/test/hello  
界面输出： userhellondex

访问：http://localhost/
界面输出：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 24 13:58:06 CST 2017
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/views/index.jsp

访问：http://localhost/user/login
界面输出：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 24 13:54:32 CST 2017
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/views/user/userLogin.jsp

**Comment by vito16** [comment]
@BruceOuyang 你尝试一下其他端口启动呢。我这里8081端口测试，是没有问题的。

**Comment by vito16** [comment]
@BruceOuyang 你尝试一下其他端口启动呢。我这里8081端口测试，是没有问题的。

**Comment by BruceOuyang** [comment]
@vito16 页面出来了，跟端口号无关，是我本地环境造成的
