### ISSUE TITLE
首页公告bug & 管理公告bug 同一类 & 公告管理页面跳转不对

### ISSUE THREAD

**Issue by BruceOuyang** [vito16/shop#27]
## 首页公告bug

访问地址：http://localhost/news/
响应信息：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 26 14:03:56 CST 2017
There was an unexpected error (type=Internal Server Error, status=500).
'end' < 0

## 管理公告bug

访问地址：http://localhost/news/admin/admin  （此处页面上点击访问少了个/admin）
响应信息：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 26 14:08:12 CST 2017
There was an unexpected error (type=Internal Server Error, status=500).
'end' < 0

**Comment by BruceOuyang** [comment]
@vito16 后台的订单管理，页面上点击的连接也不对 
访问地址：http://localhost/order/admin   （最后边加个 / 就出来了）
响应：
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 26 14:12:29 CST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by vito16** [comment]
各个URL还得重新规划下，我晚点有时间重构下。   ；）

**Comment by BruceOuyang** [comment]
@vito16 OK
