### ISSUE TITLE
项目mvn clean install 出错！

### ISSUE THREAD

**Issue by Surflyan** [vito16/shop#31]
![image](https://user-images.githubusercontent.com/22428303/40279051-a6c534b4-5c6e-11e8-94ad-5bd33f9f0830.png)

使用eclipse maven 插件，出现如上错误。
本地配置mvn 3.5.0，jdk1.8，使用本地mvn ，执行mvn clean install ，出现如下错误：
![image](https://user-images.githubusercontent.com/22428303/40279072-134e1e3e-5c6f-11e8-8715-dc6635c428fd.png)
对maven 不太熟悉，尝试了没解决。请教大佬们问题在哪里，怎样解决。

**Comment by vito16** [comment]
重新`git pull`一下，再试试

**Comment by Surflyan** [comment]
还是一样的报一样的错误

**Comment by vshai** [comment]
请问最后这个怎么解决的啊？我将项目在idea中导入，出现了依赖错误。从网上查了很多方法都没有解决。
