### ISSUE TITLE
项目branch

### ISSUE THREAD

**Issue by tanzhonghua** [vito16/shop#40]
这个项目的结构与分支，哪个是最新的啊？以及区别是什么？可以简单说一说吗？

**Comment by vito16** [comment]
master是之前最新的，也是可用的  
refactor是后面我修改了一些东西，以及替换jsp为thymeleaf做得一些重构工作，不过模板有些还没改完，所以没合并到master，有点忙。
其他两个分支废弃了

**Comment by tanzhonghua** [comment]
ok,thanks.
