### ISSUE TITLE
部署的时候遇到一些问题。

### ISSUE THREAD

**Issue by Wozhizxy** [vito16/shop#51]
部署之后尝试添加商品提示创建时间不能为空，但是翻代码相关部分发现是设置了这个属性的。

**Comment by chenboom** [comment]
您的来信已收到，谢谢。	    ——陈波This is an automatic reply, confirming that your e-mail was received. Thank you.

**Comment by chenboom** [comment]
您的来信已收到，谢谢。	    ——陈波This is an automatic reply, confirming that your e-mail was received. Thank you.
